/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ttcs.quanlyhdnk.component.notification;

import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import ttcs.quanlyhdnk.DAO.NotificationData;
import ttcs.quanlyhdnk.model.ThongBao;


/**
 *
 * @author ADMIN
 */
public class NotificationDialog extends javax.swing.JDialog {

    
//    public NotificationDialog(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
//        initComponents();
//    }
    List <ThongBao> notifcations = new ArrayList<>();
        public NotificationDialog(java.awt.Frame parent, boolean modal,String idAccount) {
        super();
        initComponents();
        this.getContentPane().setBackground(Color.GRAY);
        jdlFullNotification.getContentPane().setBackground(Color.GRAY);
        jdlFullNotification.setLocationRelativeTo(null);
        //setdata
        
        notifcations = loadNotification(idAccount);
        loadTop6NotificationPanels(notifcations);
        
        loadFullNotificationPanels(notifcations);
        setSizeNotificationMain(12);
    }
    private void setSizeNotificationMain(int soLuong){
        Dimension dimension = new Dimension(pnlFullNotificationBody.getWidth(),(int)(soLuong*52 + 4));
        pnlFullNotificationBody.setPreferredSize(dimension);
    }
    
    
    private List<ThongBao> loadNotification(String IdAccount){
        List<ThongBao> notifications = new ArrayList<>();
        
        try { 
            NotificationData daoList = new NotificationData();     
            notifications = daoList.getNotificationsDB(IdAccount);
        } catch (Exception ex) {
            Logger.getLogger(NotificationDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return notifications;
    }
    
    private void loadTop6NotificationPanels(List<ThongBao> notifications){
        pnlNotificationBody.removeAll();
        int sizeOfNotificationList= notifications.size();
                if(sizeOfNotificationList<6) btnMoreNotifi.setEnabled(false);
        if(!notifications.isEmpty()){
            for(int index =0;index<Math.min(6,sizeOfNotificationList);++index){
             //   System.out.println(notifications.get(index).getId());
                NotificationPanel notificationPanel = new  NotificationPanel(notifications.get(index));
                pnlNotificationBody.add(notificationPanel);
            }
        }
        pnlNotificationBody.revalidate();
        pnlNotificationBody.repaint();
    }
    
    private void loadFullNotificationPanels(List<ThongBao> notifications){
        pnlFullNotificationBody.removeAll();
        if(!notifications.isEmpty()){
            for(int index =0;index<notifications.size();++index){
                System.out.println(notifications.get(index).getId());
                NotificationLargePanel notificationPanel = new  NotificationLargePanel(notifications.get(index));
                pnlFullNotificationBody.add(notificationPanel);
            }
        }
        pnlFullNotificationBody.revalidate();
        pnlFullNotificationBody.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdlFullNotification = new javax.swing.JDialog();
        pnlNotificationTitle1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlFullNotificationBody = new javax.swing.JPanel();
        notificationLargePanel1 = new ttcs.quanlyhdnk.component.notification.NotificationLargePanel();
        notificationLargePanel2 = new ttcs.quanlyhdnk.component.notification.NotificationLargePanel();
        notificationLargePanel3 = new ttcs.quanlyhdnk.component.notification.NotificationLargePanel();
        notificationLargePanel4 = new ttcs.quanlyhdnk.component.notification.NotificationLargePanel();
        notificationLargePanel5 = new ttcs.quanlyhdnk.component.notification.NotificationLargePanel();
        notificationLargePanel6 = new ttcs.quanlyhdnk.component.notification.NotificationLargePanel();
        notificationLargePanel7 = new ttcs.quanlyhdnk.component.notification.NotificationLargePanel();
        notificationLargePanel8 = new ttcs.quanlyhdnk.component.notification.NotificationLargePanel();
        notificationLargePanel9 = new ttcs.quanlyhdnk.component.notification.NotificationLargePanel();
        notificationLargePanel10 = new ttcs.quanlyhdnk.component.notification.NotificationLargePanel();
        notificationLargePanel11 = new ttcs.quanlyhdnk.component.notification.NotificationLargePanel();
        notificationLargePanel12 = new ttcs.quanlyhdnk.component.notification.NotificationLargePanel();
        pnlNotificationBody = new javax.swing.JPanel();
        notificationPanel1 = new ttcs.quanlyhdnk.component.notification.NotificationPanel();
        notificationPanel2 = new ttcs.quanlyhdnk.component.notification.NotificationPanel();
        notificationPanel3 = new ttcs.quanlyhdnk.component.notification.NotificationPanel();
        notificationPanel4 = new ttcs.quanlyhdnk.component.notification.NotificationPanel();
        notificationPanel5 = new ttcs.quanlyhdnk.component.notification.NotificationPanel();
        notificationPanel7 = new ttcs.quanlyhdnk.component.notification.NotificationPanel();
        btnMoreNotifi = new javax.swing.JLabel();
        pnlNotificationTitle = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jdlFullNotification.setMinimumSize(new java.awt.Dimension(490, 600));
        jdlFullNotification.setResizable(false);
        jdlFullNotification.setSize(new java.awt.Dimension(490, 700));

        pnlNotificationTitle1.setBackground(new java.awt.Color(255, 255, 255));
        pnlNotificationTitle1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                pnlNotificationTitle1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        pnlNotificationTitle1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pnlNotificationTitle1FocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Thông báo");

        javax.swing.GroupLayout pnlNotificationTitle1Layout = new javax.swing.GroupLayout(pnlNotificationTitle1);
        pnlNotificationTitle1.setLayout(pnlNotificationTitle1Layout);
        pnlNotificationTitle1Layout.setHorizontalGroup(
            pnlNotificationTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNotificationTitle1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNotificationTitle1Layout.setVerticalGroup(
            pnlNotificationTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlFullNotificationBody.setBackground(new java.awt.Color(229, 229, 229));
        pnlFullNotificationBody.setMaximumSize(new java.awt.Dimension(490, 32767));
        pnlFullNotificationBody.setMinimumSize(new java.awt.Dimension(490, 490));
        pnlFullNotificationBody.setName(""); // NOI18N
        pnlFullNotificationBody.setPreferredSize(new java.awt.Dimension(490, 554));
        pnlFullNotificationBody.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));
        pnlFullNotificationBody.add(notificationLargePanel1);
        pnlFullNotificationBody.add(notificationLargePanel2);
        pnlFullNotificationBody.add(notificationLargePanel3);
        pnlFullNotificationBody.add(notificationLargePanel4);
        pnlFullNotificationBody.add(notificationLargePanel5);
        pnlFullNotificationBody.add(notificationLargePanel6);
        pnlFullNotificationBody.add(notificationLargePanel7);
        pnlFullNotificationBody.add(notificationLargePanel8);
        pnlFullNotificationBody.add(notificationLargePanel9);
        pnlFullNotificationBody.add(notificationLargePanel10);
        pnlFullNotificationBody.add(notificationLargePanel11);
        pnlFullNotificationBody.add(notificationLargePanel12);

        jScrollPane2.setViewportView(pnlFullNotificationBody);

        javax.swing.GroupLayout jdlFullNotificationLayout = new javax.swing.GroupLayout(jdlFullNotification.getContentPane());
        jdlFullNotification.getContentPane().setLayout(jdlFullNotificationLayout);
        jdlFullNotificationLayout.setHorizontalGroup(
            jdlFullNotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNotificationTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        jdlFullNotificationLayout.setVerticalGroup(
            jdlFullNotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdlFullNotificationLayout.createSequentialGroup()
                .addComponent(pnlNotificationTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.darkGray);
        setMinimumSize(new java.awt.Dimension(334, 384));
        setUndecorated(true);
        setSize(new java.awt.Dimension(334, 384));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        pnlNotificationBody.setBackground(new java.awt.Color(229, 229, 229));
        pnlNotificationBody.setMaximumSize(new java.awt.Dimension(330, 322));
        pnlNotificationBody.setMinimumSize(new java.awt.Dimension(330, 322));
        pnlNotificationBody.setPreferredSize(new java.awt.Dimension(330, 322));
        pnlNotificationBody.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 2, 3));
        pnlNotificationBody.add(notificationPanel1);
        pnlNotificationBody.add(notificationPanel2);
        pnlNotificationBody.add(notificationPanel3);
        pnlNotificationBody.add(notificationPanel4);
        pnlNotificationBody.add(notificationPanel5);
        pnlNotificationBody.add(notificationPanel7);

        btnMoreNotifi.setBackground(new java.awt.Color(255, 255, 255));
        btnMoreNotifi.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnMoreNotifi.setForeground(new java.awt.Color(0, 102, 204));
        btnMoreNotifi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMoreNotifi.setText("Xem thêm");
        btnMoreNotifi.setOpaque(true);
        btnMoreNotifi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMoreNotifiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMoreNotifiMouseEntered(evt);
            }
        });

        pnlNotificationTitle.setBackground(new java.awt.Color(255, 255, 255));
        pnlNotificationTitle.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                pnlNotificationTitleAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        pnlNotificationTitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pnlNotificationTitleFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Thông báo");

        javax.swing.GroupLayout pnlNotificationTitleLayout = new javax.swing.GroupLayout(pnlNotificationTitle);
        pnlNotificationTitle.setLayout(pnlNotificationTitleLayout);
        pnlNotificationTitleLayout.setHorizontalGroup(
            pnlNotificationTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNotificationTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNotificationTitleLayout.setVerticalGroup(
            pnlNotificationTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMoreNotifi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNotificationTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNotificationBody, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(pnlNotificationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlNotificationBody, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMoreNotifi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoreNotifiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoreNotifiMouseClicked
       // if(btnMoreNotifi.isEnabled()){
            
            jdlFullNotification.setVisible(true);
     //   }
    }//GEN-LAST:event_btnMoreNotifiMouseClicked

    private void btnMoreNotifiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoreNotifiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMoreNotifiMouseEntered

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
       this.setVisible(false);
       this.dispose();
        
    }//GEN-LAST:event_formFocusLost

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited

       
    }//GEN-LAST:event_formMouseExited

    private void pnlNotificationTitleAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_pnlNotificationTitleAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlNotificationTitleAncestorAdded

    private void pnlNotificationTitleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnlNotificationTitleFocusLost

    }//GEN-LAST:event_pnlNotificationTitleFocusLost

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void pnlNotificationTitle1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_pnlNotificationTitle1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlNotificationTitle1AncestorAdded

    private void pnlNotificationTitle1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnlNotificationTitle1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlNotificationTitle1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], String idAccount) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotificationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotificationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotificationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotificationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NotificationDialog dialog = new NotificationDialog(new javax.swing.JFrame(), true,idAccount);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnMoreNotifi;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog jdlFullNotification;
    private ttcs.quanlyhdnk.component.notification.NotificationLargePanel notificationLargePanel1;
    private ttcs.quanlyhdnk.component.notification.NotificationLargePanel notificationLargePanel10;
    private ttcs.quanlyhdnk.component.notification.NotificationLargePanel notificationLargePanel11;
    private ttcs.quanlyhdnk.component.notification.NotificationLargePanel notificationLargePanel12;
    private ttcs.quanlyhdnk.component.notification.NotificationLargePanel notificationLargePanel2;
    private ttcs.quanlyhdnk.component.notification.NotificationLargePanel notificationLargePanel3;
    private ttcs.quanlyhdnk.component.notification.NotificationLargePanel notificationLargePanel4;
    private ttcs.quanlyhdnk.component.notification.NotificationLargePanel notificationLargePanel5;
    private ttcs.quanlyhdnk.component.notification.NotificationLargePanel notificationLargePanel6;
    private ttcs.quanlyhdnk.component.notification.NotificationLargePanel notificationLargePanel7;
    private ttcs.quanlyhdnk.component.notification.NotificationLargePanel notificationLargePanel8;
    private ttcs.quanlyhdnk.component.notification.NotificationLargePanel notificationLargePanel9;
    private ttcs.quanlyhdnk.component.notification.NotificationPanel notificationPanel1;
    private ttcs.quanlyhdnk.component.notification.NotificationPanel notificationPanel2;
    private ttcs.quanlyhdnk.component.notification.NotificationPanel notificationPanel3;
    private ttcs.quanlyhdnk.component.notification.NotificationPanel notificationPanel4;
    private ttcs.quanlyhdnk.component.notification.NotificationPanel notificationPanel5;
    private ttcs.quanlyhdnk.component.notification.NotificationPanel notificationPanel7;
    private javax.swing.JPanel pnlFullNotificationBody;
    private javax.swing.JPanel pnlNotificationBody;
    private javax.swing.JPanel pnlNotificationTitle;
    private javax.swing.JPanel pnlNotificationTitle1;
    // End of variables declaration//GEN-END:variables
}
