/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ttcs.quanlyhdnk.form;

import ttcs.quanlyhdnk.model.ThongBao;
import ttcs.quanlyhdnk.util.DateTimeUtil;

/**
 *
 * @author ADMIN
 */
public class NotificationLargePanel extends javax.swing.JPanel {

    private ThongBao thongBao = new ThongBao();
    public NotificationLargePanel(){
        initComponents();
    }
    
    public NotificationLargePanel(ThongBao thongBao){
        initComponents();
        this.thongBao=thongBao;
        setContentForCard();
        setContentForDlg();
    }
    private void setContentForCard(){
        lblTitle.setText(thongBao.getTitle());
        lblPostingName.setText(thongBao.getIdUser());
        lblTimePost.setText(DateTimeUtil.LocalDateTimeToStringDay(thongBao.getPostingTime()));
    }
    private void setContentForDlg(){
        taTitleDlg.setText(thongBao.getTitle());
        taPostingNameDlg.setText(thongBao.getIdUser());
        lblTimePostDlg.setText(DateTimeUtil.LocalDateTimeToStringDay(thongBao.getPostingTime()));
        taContentDlg.setText(thongBao.getContent());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgNotification = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taTitleDlg = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTimePostDlg = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taContentDlg = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        taPostingNameDlg = new javax.swing.JTextArea();
        lblTimePost = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPostingName = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        dlgNotification.setMinimumSize(new java.awt.Dimension(555, 370));
        dlgNotification.setSize(new java.awt.Dimension(555, 400));
        dlgNotification.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dlgNotificationFocusLost(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));

        jScrollPane2.setBorder(null);

        taTitleDlg.setEditable(false);
        taTitleDlg.setBackground(new java.awt.Color(216, 216, 216));
        taTitleDlg.setColumns(20);
        taTitleDlg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        taTitleDlg.setForeground(new java.awt.Color(0, 153, 204));
        taTitleDlg.setRows(2);
        taTitleDlg.setBorder(null);
        jScrollPane2.setViewportView(taTitleDlg);

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Từ:");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Lúc:");

        lblTimePostDlg.setForeground(new java.awt.Color(102, 102, 102));
        lblTimePostDlg.setText("00:00 01-01-2024");

        taContentDlg.setEditable(false);
        taContentDlg.setBackground(new java.awt.Color(242, 242, 242));
        taContentDlg.setColumns(20);
        taContentDlg.setForeground(new java.awt.Color(51, 51, 51));
        taContentDlg.setRows(5);
        jScrollPane3.setViewportView(taContentDlg);

        jScrollPane4.setBorder(null);

        taPostingNameDlg.setBackground(new java.awt.Color(229, 229, 229));
        taPostingNameDlg.setColumns(20);
        taPostingNameDlg.setForeground(new java.awt.Color(51, 51, 51));
        taPostingNameDlg.setRows(2);
        taPostingNameDlg.setAutoscrolls(false);
        taPostingNameDlg.setBorder(null);
        jScrollPane4.setViewportView(taPostingNameDlg);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTimePostDlg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTimePostDlg))
                .addContainerGap())
        );

        javax.swing.GroupLayout dlgNotificationLayout = new javax.swing.GroupLayout(dlgNotification.getContentPane());
        dlgNotification.getContentPane().setLayout(dlgNotificationLayout);
        dlgNotificationLayout.setHorizontalGroup(
            dlgNotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgNotificationLayout.setVerticalGroup(
            dlgNotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(460, 50));
        setPreferredSize(new java.awt.Dimension(460, 50));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblTimePost.setForeground(new java.awt.Color(102, 102, 102));
        lblTimePost.setText("00:00 44-12-2024");

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Lúc:");

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Từ:");

        lblPostingName.setForeground(new java.awt.Color(102, 102, 102));
        lblPostingName.setText("ten người đăng");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 153, 204));
        lblTitle.setText("Tieu de");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPostingName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTimePost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTimePost)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(lblPostingName))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void dlgNotificationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dlgNotificationFocusLost

    }//GEN-LAST:event_dlgNotificationFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dlgNotification;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblPostingName;
    private javax.swing.JLabel lblTimePost;
    private javax.swing.JLabel lblTimePostDlg;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea taContentDlg;
    private javax.swing.JTextArea taPostingNameDlg;
    private javax.swing.JTextArea taTitleDlg;
    // End of variables declaration//GEN-END:variables
}
